### ISSUE TITLE
Get 3d position and iris

### ISSUE THREAD

**Issue by fire** [purgeme/godot_mediapipe_module#1]
Hi!

We also worked on this and was able to get a few more outputs like 3d position and iris.

https://github.com/V-Sekai/mediapipe/commit/22727f7f9e404d5c4c0fe139c3bbc0e732ce544c

**Comment by purgeme** [comment]
Custom graphs should be supported. So the holistic_with_iris.pbtxt graph should also work here.

**Comment by purgeme** [comment]
Yep, works just fine.
